### Performance & Frame Metrics
fps
frametime=1
frame_timing=1
fps_limit=180,120,60,0

### Hardware Temps & Usage
gpu_stats
gpu_temp
gpu_core_clock
gpu_mem_clock
gpu_power

cpu_stats
cpu_temp
cpu_mhz
cpu_power

vram
ram

### Appearance & Layout
hud_compact=0
position=top-left
background_alpha=0.4
font_size=20
text_color=FFFFFF
gpu_color=2E7D32
cpu_color=0288D1

### Interactive Keybinds
toggle_hud=Shift_R+F12
toggle_logging=Shift_R+F11
reload_cfg=Shift_R+F10
toggle_fps_limit=Shift_R+F9
