[main]
# font=JetBrains Mono Nerd Font:size=18
font=JetBrains Mono Nerd Font:size=11
width=60
lines=10
horizontal-pad=5
vertical-pad=5
inner-pad=1
anchor=center
image-size-ratio=0.5
border-width=200
border-radius=0
selection-radius=0
line-height=18
terminal=kitty

[colors]
background=2e3440ff  # Nord 0 (Polar Night)
text=d8dee9ff       # Nord 4 (Snow Storm)
match=88c0d0ff      # Nord 8 (Frost)
selection=434c5eff  # Nord 1 (Polar Night)
selection-text=eceff4ff # Nord 5 (Snow Storm)
border=5e81acff     # Nord 10 (Frost)
input=d8dee9ff      # Nord 4 (Snow Storm)
[border]
width=1
radius=0
